### PR TITLE
added final support for hardware encoding with qsv, and nvmpi

### PR DESCRIPTION
**Pull request by HawtDogFlvrWtr**
Testing is finished for QSV. Though driver install is difficult, it works as intended if you install the intel drivers using their instructions. I've also added support for NVMPI, which is the ffmpeg decoder/encoder (https://github.com/jocover/jetson-ffmpeg) type for nvidia jetson devices. This is what i'm using now as my motioneye server, and it performs under 50% cpu with 4x720p cameras leveraging hardware nvmpi encoding and decoding (motion extra param: netcam_decoder h264_nvmpi)

### CODE REVIEW

**Comment by ccrisan** [comment]
Looks good to me, just like the previous one. I don't see any reason why this wouldn't be merged.

**Comment by antonoal** [comment]
Hi @HawtDogFlvrWtr 
Do you have by any chance any notes how to install the intel driver? 
Cheers, Alex

**Comment by HawtDogFlvrWtr** [comment]
> Hi @HawtDogFlvrWtr
> Do you have by any chance any notes how to install the intel driver?
> Cheers, Alex

sure do

https://medium.com/@fanzongshaoxing/use-ffmpeg-to-decode-h-264-stream-with-nvidia-gpu-acceleration-16b660fd925d

This is the link I used to compile ffmpeg

**Comment by HawtDogFlvrWtr** [comment]
This link has a nice install guide for debian based systems. 
https://gist.github.com/andrearug/ee461152acfbbd3f52b3bb9ffb55b6b8

This is the white paper by intel also
https://www.intel.com/content/dam/www/public/us/en/documents/white-papers/quicksync-video-ffmpeg-install-valid.pdf

**Comment by antonoal** [comment]
Awesome! Thanks a lot!

**Comment by antonoal** [comment]
Apologies for commenting on a very old PR. 
I've now built FFmpeg with qsv support and then realised that I can't have it in a docker container where I'm running motioneye. 
Can you advise by any chance if I can get it working in docker?

**Pull request merged**
