### PR TITLE
clean cloud (gdrive only)

### LINKED ISSUE #1094: [feature] removing old files on Google drive
Have used `motioneye` for a month now, quite happy and thanks for this project.
Found a similar feature request #200 but I am raising a new one here:

I am preserving movies for 5 days and uploading them to my Google drive.
Old files and folders on local RPI are being removed well (`_remove_older_files` of `mediafiles.py`) but on Google drive, the named folder seems to keep growing and I would have to visit my drive periodically to remove old ones manually (if I am missing something here please advise).

Certainly Google REST API seems to allow removing files and I am interested in contribute to this project   if some guidance is provided (I am web developer, quite new to python):

- how to make code change and test it locally?
- can I just reuse key and tokens in `uploadservices.json`?

### PR DESCRIPTION
**Pull request by bob-lee**
Resolves #1094.
Added an abstract function `UploadService.clean_cloud` and implemented `GoogleDrive.clean_cloud`.
When `mediafiles.py` removes a old local folder, it calls `clean_cloud` to remove old cloud folders as well that do not exist in local.

### CODE REVIEW

**Comment by bob-lee** [comment]
@ccrisan Would you be available to review this sometime? I am running this on my `Pi Zero` with 2 days file persistence setting and `gdrive` seems to get cleaned daily to contain only movies for last 2 days.

**Comment by ccrisan** [comment]
@bob-lee on a first glance this looks good. However it would need more testing, since removing users files from the cloud can be very nasty if done wrong. This is why I never wanted to implement this feature.

I would merge if it were disabled by default and if there were a user option to enable this, with a big effing warning, just like the one we have for preserving local media files for limited periods of time.

I saw that you at least thought of such an option:

    #clean_cloud_enabled = camera_config.get('@clean_cloud_enabled'` in your PR

Could you please actually implement this?

**Comment by bob-lee** [comment]
@ccrisan Thanks for feedback, would love to implement a new option, say `clean_cloud_enabled`. Haven't followed code regarding how options work. Any guidance on following things will be appreciated:

- will it be a new checkbox on `File Storage` section on GUI, turned off by default?
- how `thread_x.conf` file is initialized?

**Comment by ccrisan** [comment]
> will it be a new checkbox on File Storage section on GUI, turned off by default?

Yes, that would be the best choice IMHO.

> how thread_x.conf file is initialized?

See `motioneye/config.py: _set_default_motion_camera`.

**Comment by bob-lee** [comment]
@ccrisan Have added [another commit](https://github.com/ccrisan/motioneye/pull/1118/commits/7584987b0276be9f5a83167f90fe08c7d35eb02c) and getting error below when I click `Apply` button with some changes made on `File Storage` or `Movies` sections:

```
Jan 24 17:45:37 raspberrypi meyectl[224]:    ERROR: 'clean_cloud_enabled'
Jan 24 17:45:37 raspberrypi meyectl[224]: Traceback (most recent call last):
Jan 24 17:45:37 raspberrypi meyectl[224]:   File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1548, in _stack_context_handle_exception
Jan 24 17:45:37 raspberrypi meyectl[224]:     raise_exc_info((type, value, traceback))
Jan 24 17:45:37 raspberrypi meyectl[224]:   File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1756, in wrapper
Jan 24 17:45:37 raspberrypi meyectl[224]:     result = method(self, *args, **kwargs)
Jan 24 17:45:37 raspberrypi meyectl[224]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/handlers.py", line 292, in post
Jan 24 17:45:37 raspberrypi meyectl[224]:     self.set_config(camera_id)
Jan 24 17:45:37 raspberrypi meyectl[224]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/handlers.py", line 205, in wrapper
Jan 24 17:45:37 raspberrypi meyectl[224]:     return func(self, *args, **kwargs)
Jan 24 17:45:37 raspberrypi meyectl[224]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/handlers.py", line 527, in set_config
Jan 24 17:45:37 raspberrypi meyectl[224]:     set_camera_config(int(key), cfg, check_finished)
Jan 24 17:45:37 raspberrypi meyectl[224]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/handlers.py", line 374, in set_camera_config
Jan 24 17:45:37 raspberrypi meyectl[224]:     local_config = config.motion_camera_ui_to_dict(ui_config, local_config)
Jan 24 17:45:37 raspberrypi meyectl[224]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/config.py", line 759, in motion_camera_ui_to_dict
Jan 24 17:45:37 raspberrypi meyectl[224]:     '@clean_cloud_enabled': ui['clean_cloud_enabled'],
Jan 24 17:45:37 raspberrypi meyectl[224]: KeyError: 'clean_cloud_enabled'
Jan 24 17:45:37 raspberrypi meyectl[224]:    ERROR: 500 POST /config/0/set/?_=1548305140853&_username=admin&_signature=955efc00831a3aac2d23f3655a1495f9ad8b2689 (192.168.1.65) 63.32ms
```
GUI shows a new option ok but `ui['clean_cloud_enabled']` seems failing for some reason..?

image

**Comment by bob-lee** [comment]
@ccrisan Ignore previous comment, it was a matter of emptying browser cache and load a new `main.js`, will continue to test.

**Comment by bob-lee** [comment]
@ccrisan `clean_cloud_enabled` option implemented and tested. Please have a look.
cleancloudwarning

**Comment by ccrisan** [comment]
@bob-lee will take a look and get back to you as soon as I get some spare time.

**Comment by ccrisan** [comment]
@bob-lee I've reviewed your PR and things generally look good. In my tests, the functionality works well. There's one single problem that needs to be addressed somehow: non-Google Drive users will expect this to work, given the current UI, for their upload method.

We should either tell them somehow, from the UI, that this function only works for Google Drive, or implement it for the rest of upload providers.

**Comment by bob-lee** [comment]
@ccrisan Thanks for feedback, I thought it is ok as non-gdrive service wouldn't break at least as UploadService has a virtual method (not sure this is the right term in python) `clean_cloud`. But that's a valid point I guess. Will you be happy if GUI doesn't allow to enable the option for non-gdrive service and the option's help text shows some additional explanation like below?

"enable this to delete the uploaded media files on cloud as well when the local media files get deleted according to file persistence setting, _available only for gdrive for now_"

**Comment by ccrisan** [comment]
> Will you be happy if GUI doesn't allow to enable the option for non-gdrive service and the option's help text shows some additional explanation like below? 

That's the best way to go, I think. Simply not displaying the option for non-gdrive services would be perfect.

**Comment by bob-lee** [comment]
@ccrisan fixed and tested.
https://github.com/ccrisan/motioneye/pull/1118/commits/c4244e796ddddf927d898672f28ecdb16eb7f96f

**Comment by ccrisan** [comment]
Thanks!

**Pull request merged**
