### PR TITLE
Fix for issue #1001

### PR DESCRIPTION
**Pull request by kleini**
Install necessary python libraries and system tools for timezone management

### CODE REVIEW

**Comment by kleini** [comment]
This should fix issue #1001

**Comment by ccrisan** [comment]
@kleini is this ready to be merged?

**Comment by kleini** [comment]
> @kleini is this ready to be merged?

People reporting issue #1001 need to test the fix.

**Comment by kleini** [comment]
@ccrisan can be merged as tests are successful.

**Pull request merged**
