### PR TITLE
rtsp support for docker

### PR DESCRIPTION
**Pull request by donvipre**
added the mr-dave motion fork to the docker image

### CODE REVIEW

**Comment by ccrisan** [comment]
Thanks. I don't have the time and the means to test this change but I believe you know what you're doing there :)

**Comment by jeff-h** [comment]
@donvipre it would be awesome if you had the time to put together some notes on getting this up and running in Docker. Even something really brief would help. I'm happy to flesh it out and stick it in the wiki.

**Comment by ccrisan** [comment]
I'm happy to add more instructions to the wiki. I'd also be happy to add more contributors to the wiki, in general.

**Comment by jeff-h** [comment]
Ha sorry! That was a little presumptuous... I thought Github wikis were all publicly read/write :)

**Comment by jeff-h** [comment]
@ccrisan I've gotten my motionEye docker container up and running pretty well. I'm happy to document it in the wiki  if you would like.

**Comment by ccrisan** [comment]
@jeff-h I've just made you a collaborator. Please let me know if you now have (or don't have) access to the wiki. And thanks in advance for your contribution.

**Comment by jeff-h** [comment]
Thanks! Unfortunately I don't have write access to the wiki yet though.

**Comment by donvipre** [comment]
Sorry,
i had no time to answer.. i will look how i can help.

Calin Crisan <notifications@github.com> schrieb am Mi., 24. Aug. 2016,
08:50:

**Comment by ccrisan** [comment]
@jeff-h, the wiki setting says *Restrict editing to collaborators only*. Also, in the collaborators page, next to your username they say *Awaiting for jeff-h's response*. Have you accepted the invitation? This is the link I assumed you received by email: https://github.com/ccrisan/motioneye/invitations.

**Comment by jeff-h** [comment]
So sorry — I didn't realise I had to accept the invitation lol All good now :)

**Pull request merged**
