### PR TITLE
Travis CI: Use flake8 to find Python 3 compatibility issues

### PR DESCRIPTION
**Pull request by cclauss**
Tests related to #1572

### CODE REVIEW

**Comment by kleini** [comment]
We should merge this to the python3 branch. Changed therefore the target branch. Furthermore those flake8 checks should be a separate parallel running stage, otherwise the docker images are not built for testing if flake8 fails.

**Comment by kleini** [comment]
Thanks to @cclauss, this flake8 makes necessary changes very transparent.

**Comment by cclauss** [comment]
https://flake8.pycqa.org/en/latest/user/error-codes.html

On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead these tests are focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled language but in a dynamic language like Python they result in the script halting/crashing on the user.
* F63 tests are usually about the confusion between identity and equality in Python.  Use ==/!= to compare str, bytes, and int literals is the classic case.  These are areas where __a == b__ is True but __a is b__ is False (or vice versa).  Python >= 3.8 will raise SyntaxWarnings on these instances.
* F7 tests logic errors and syntax errors in type hints
* F82 tests are almost always _undefined names_ which are usually a sign of a typo, missing imports, or code that has not been ported to Python 3.  These also would be compile-time errors in a compiled language but in Python a __NameError__ is raised which will halt/crash the script on the user.

**Comment by kleini** [comment]
Yes, I understand the tests. But anyways, the resulting Docker images from the automated Travis CI builds already allow to start motioneye and to add a network camera. This would get lost with having your changes included. Once everything is working and stable and released, these checks should be mandatory for every code change. But this does not make sense in development phases.

**Comment by cclauss** [comment]
The Python 3 branch is not a production branch, is it?

**Comment by kleini** [comment]
No, `python3` is not a production branch, it is development in progress. And personally I use the Docker images to test motioneye and I would like to have those images build for other possible contributors.

**Comment by cclauss** [comment]
Fixed remaining flake8 issues and removed __--exit_zero__

**Comment by cclauss** [comment]
> the resulting Docker images from the automated Travis CI builds already allow to start motioneye and to add a network camera. This would get lost with having your changes included. 

Now that the flake8 tests pass, this is no longer true.

**Comment by kleini** [comment]
That is great work! Thank you very much. @ccrisan I think, we can merge this now into python3 branch and continue with functional testing.

**Comment by ccrisan** [comment]
> That is great work! Thank you very much. @ccrisan I think, we can merge this now into python3 branch and continue with functional testing.

@kleini sure, let's have it merged. @cclauss thanks for your work!

**Pull request merged**
