### PR TITLE
Fix frame static assets link

### PR DESCRIPTION
**Pull request by Mirio**
Fix assets link on a "frame" page.

### CODE REVIEW

**Comment by ccrisan** [comment]
Why do you think these links have to be absolute? Recently we've made them relative so that reverse proxy mechanisms could "hide" motionEye behind any path.

**Comment by Mirio** [comment]
Because if you want to expose the only "frame" link with this scenario (below) you can't do that without this changes.
Nginx:
`
location /static {
        proxy_pass       http://127.0.0.1:6000;
        proxy_set_header Host      $host;
        proxy_set_header X-Real-IP $remote_addr;
}

location /picture {
	proxy_pass       http://127.0.0.1:6000;
	proxy_set_header Host      $host;
	proxy_set_header X-Real-IP $remote_addr;
}
`

**Comment by ccrisan** [comment]
I beg to differ. When using the following nginx location configuration:

    location /cams/ {
        proxy_pass http://127.0.0.1:8765/;
    }

I can easily access `http://localhost/cams/picture/1/frame/`. This was in fact the point of having all paths relative.

**Comment by Mirio** [comment]
Nope, below the result:

$ curl http://127.0.0.1:6000/cams/picture/1/frame/
`{"error": "not found"}% `

$ curl http://127.0.0.1:6000/picture/1/frame/
`[....]`

**Comment by ccrisan** [comment]
Can I see your nginx config?

**Comment by Mirio** [comment]
This curl posted is directly to motioneye.
I use the version 0.36 from pypi

**Comment by ccrisan** [comment]
1. Then your curl command doesn't make any sense. The `/cams` prefix is meant to be used with a reverse proxy (e.g. nginx). Obviously you'll get a "not found" error if you request it directly to motionEye.
2. Please use 0.36.1, which incorporates some fixes with regards to frame relative paths.

**Comment by Mirio** [comment]
ok i will try it, what settings i need to set on nginx?

**Comment by ccrisan** [comment]
Mine :) `proxy_pass http://127.0.0.1:8765/;`

**Comment by Mirio** [comment]
Nope, the results are same.
Nginx config:
```
                location /cams/ {
                        proxy_pass       http://127.0.0.1:6000/;
                        proxy_set_header Host      $host;
                        proxy_set_header X-Real-IP $remote_addr;
                }
```
motionEye Version = 0.36.1
Motion Version = 4.0.1

Output:
`{"error": "not found"}`

**Comment by ccrisan** [comment]
And what does your curl command line look like when you get `{"error": "not found"}`?

**Comment by Mirio** [comment]
```
curl http://127.0.0.1:<nginx_port>/cams/picture/1/frame/
```

**Comment by ccrisan** [comment]
That's strange. And what does the motioneye log say about that request?

**Comment by Mirio** [comment]
Below the stderr:
```
 WARNING: 404 GET /cams/picture/1/frame (xxx.xxx.xxx.xxx) 2.35ms
   ERROR: HTTP 404: Not Found (not found)
```
On motion.log don't result anything.

**Comment by ccrisan** [comment]
Then something's wrong with your nginx configuration. It should *not* pass the prefix to the proxied server. Are you 100% you have a trailing slash at the end of your proxy_pass directive?

**Comment by Mirio** [comment]
Oh i've try to restart nginx and now seems to be work.
I suggest you to document it, you can close this pull request.

**Pull request closed without merging**
