### PR TITLE
Add mosquitto clients & upgrade

### LINKED ISSUE #877: Package mosquitto-clients missing in Docker
Hello, 

I'm using Docker version on RPi3 installed like this instruction: https://github.com/ccrisan/motioneye/wiki/Install-In-Docker

docker run --name="motioneye" \
    -p 8765:8765 \
    --hostname="motioneye" \
    -v /etc/localtime:/etc/localtime:ro \
    -v /etc/motioneye:/etc/motioneye \
    -v /var/lib/motioneye:/var/lib/motioneye \
    --restart="always" \
    ccrisan/motioneye:dev-armhf

All working good except mosquitto_pub command was not working in Motion Notifications, but after installing mosquitto-clients package inside container it started working, please add it to image

### PR DESCRIPTION
**Pull request by deece**
Closes #877 #1076

This PR:
 - adds the MQTT client 'mosquitto' to the docker image
 - Updates motion to 4.2
 - Updates the AMD64 image to Ubuntu 18.04

Tested on AMD64

### CODE REVIEW

**Comment by deece** [comment]
@kleini Yup, tested the AMD64 image. 

Libmicrohttpd12 is a new dependency for the motion 4.2 package.

motioneye

**Comment by deece** [comment]
All the cameras I use are RTSP - same as that bug report. 

That bug report may be related to ffmpeg or resolver issues:
`ffmpeg_avcodec_log: Failed to resolve hostname cam01.mac01.tuxsolutions.org`

**Comment by kleini** [comment]
Then I approve your change request except the mentioned issue #1070 . @ccrisan can you tell us something about that problem? If I understand issue #1070 correctly RTSP network cameras do not work. I exclusively use RTSP network cameras and the new image may not work for me. Will try to test the new image today.

**Comment by deece** [comment]
My RTSP cameras work, but independent testing is always good

**Comment by kleini** [comment]
This image does not work for me. I don't see the picture of the network camera in the motioneye web interface. In the logs I see:

    ERROR: mjpg client timed out receiving data for camera 1 on port 8081

although streaming is not enabled in motioneye web interface. Maybe this is the main problem with the new motion version.

**Comment by deece** [comment]
Interesting, all my cameras are h.264.

I'll split this into seperate PRs so the motion upgrade can be done independently

**Comment by kleini** [comment]
Same here. h.264 rtsp network cameras.

**Comment by ccrisan** [comment]
Guys, regarding the Motion 4.2 support question, I did not have the time yet to test motionEye with this Motion version. I can't say for sure that it is not supported by motionEye, but from their changelog, there probably are some configuration options that need to be adjusted.

**Comment by deece** [comment]
I've removed the upgrade commits from this PR, it's just the mosquitto client now.

**Comment by deece** [comment]
The contention around motion 4.2 should no longer be relevant, as I have removed the upgrade patch. This now just adds the mosquitto clients, so I presume @kleini 's approval now stands.

Is there anything else that I need to do before this can be merged?

**Pull request merged**
