### PR TITLE
added Dockerfile

### PR DESCRIPTION
**Pull request by cahna**
I created this to deploy in my home setup and thought I'd see if you'd be interested in accepting it. 

If so, I'd suggest linking the repository to docker hub as an automated build so the docker image will always be up-to-date :smiley: 

Here's an example setup:
```yaml
# docker-compose.yml
---
motioneye_data:
  image: cheine/motioneye
  entrypoint: /bin/true
  volumes:
    - /docker/motioneye/data:/var/lib/motioneye
    - /docker/motioneye/pids:/var/run/motioneye
    - /docker/motioneye/config:/etc/motioneye

motioneye:
  image: cheine/motioneye
  restart: always
  volumes_from:
    - motioneye_data
  ports:
    - 8765:8765
```

P.S. Great work! I'm so happy to have found this. Goodbye forever, zoneminder.

### CODE REVIEW

**Comment by ccrisan** [comment]
Well, I don't see why not. Thanks for your contribution. However, I'll move the `Dockerfile` to the `extra` folder (I hope that won't break anything - I don't have experience with Docker at all).

**Comment by cahna** [comment]
Happy to contribute. The `Dockerfile` doesn't depend on any build context, so the `extra` folder will work.

BTW, I'm a python developer with a lot of free time in the next few weeks. I'd be happy to spend some of that time on motioneye if you have any features/bugs outstanding.

**Comment by ccrisan** [comment]
@cahna It's great to hear that you speak python, you have some free time and you're willing to help. These three conditions have never been met before by anyone :)

Actually users have been asking me a lot to add audio support to the whole solution. Do you think you would be up to this task? Normally there are two subtasks when it comes to audio: (1) real-time transmitting of audio stream along with the video one (no recording, no touching of motion daemon) and (2) adding an audio track to the recorded movie files (involves a lot of work and dealing with motion C source code). What do you think?

**Comment by cahna** [comment]
Sounds like a proper challenge, @ccrisan. Having audio support would be nice. Let me do some research on motion and read the motioneye code to get a better idea of what needs to be done. If you don't have any imminent deadline requirements, I'd be happy to give it a shot. 

Want to take further discussion to [gitter](https://gitter.im), irc, or email? I know I'll have questions.

**Comment by ccrisan** [comment]
(Un)fortunately there aren't any urgent issues; if there had been any, I would have gotten them fixed already :)

Regarding further discussions, sure, we could use any of them. I never used gitter before, but it seems quite nice. Let's give it a try.

**Comment by rickerd** [comment]
@cahna can you point out how to run the docker. I want to contribute to implement better use of the UI.
I don't speak Python, sadly, but i do wana contribute! :)

**Comment by jeff-h** [comment]
I've added some notes to the Wiki on running motionEye in Docker.

https://github.com/ccrisan/motioneye/wiki/Install-in-Docker

**Comment by Hard2findaNameHere** [comment]
Hi Calin, thank you for your previous help with the action buttons, my little project is working good now.   I noticed that your road map includes the possibility of audio.  Has there been any progress on this?

**Pull request merged**
