### PR TITLE
Python3 compatibility

### PR DESCRIPTION
**Pull request by ualex73**
This is my first pull request to get Python3 compatibility into motionEye. The pull makes it runs on Python2 and Python3 with the same code, only Python3 can use tornado 4.5.3 (or lower) because they changed things internally (different class/object now).

Please review it, and if any improvements are needed.

### CODE REVIEW

**Comment by ccrisan** [comment]
@ualex73 thanks for the PR. I'll review it after we manage to release 0.40 stable.

**Comment by ualex73** [comment]
:+1:

**Comment by bob-lee** [comment]
@ualex73 I tried `sudo python setup.py install` which installed on python `2.7`, giving me an error like below when testing upload service:
```
meyectl[216]:  WARNING: accessing gdrive failed: 'Module_six_moves_urllib_request' object has no attribute 'HTTPError'
```
Any command line instructions on how to install these codes for test?

**Comment by ualex73** [comment]
Thanks for testing, i fixed this in the latest commit:
https://github.com/ualex73/motioneye/commit/876a315989541a85bec0792115a76e9563541d44

**Comment by bob-lee** [comment]
@ualex73 I have tested around `gdrive` upload service and it seemed working ok. 
Not sure about the point of this PR though.. are these codes supposed to work on `python 3` as well?

**Comment by ualex73** [comment]
@bob-lee Yes, that is the main purpose of this PR, that the code is usable on Python 2 and 3 (i have it running on my dev machine in python3) ... Python 2 will go out of support in 2020, after that e.g. pip2 can stop working, etc.

**Comment by ccrisan** [comment]
@ualex73 my personal opinion on this matter is that we should concentrate our efforts on supporting *only* Python 3. There's no point in preserving Python 2 compatibility since we can soon kiss it goodbye.  I would rather spend more time helping/convincing users to switch to Python 3 than messing with six and all the 2+3 compatibility issues.

**Comment by ualex73** [comment]
@ccrisan I can make a PR with Python3 only support, it is straight forward - except for the tornado compatibility. That one takes a bit more testing to get it working with 5+.
Just let me know if you are interested in such PR, and on which version (e.g. when 0.40 is released?).

**Comment by kleini** [comment]
Let me start to prepare the according Dockerfile, so we get just runable Docker images. I don't want to mess around with installing python3 and pip3 on my production systems. And I see a lot of issues reported for motioneye, that some pip instruction or upgrade or whatever did not work as expected. It is to error prone to force users to install complex software.

**Comment by ualex73** [comment]
@kleini I use the following Docker image as base (python 3.7):
`FROM python:alpine`

Saves time to maintain the image with python3 ;-) This is the Alpine (minimal) image, so I have to compile motion during the build.

The rest of my Docker is as follows:
FROM python:alpine
ENV MOTIONEYE_VERSION 0.40rc5
ENV MOTION_VERSION 4.2.2

# MySQL/MQTT not added yet
RUN apk add --no-cache \
    bash \
    gcc \
    curl-dev \
    curl \
    musl-dev \
    jpeg-dev \
    ffmpeg \
    ffmpeg-dev \
    autoconf \
    automake \
    make \
    libmicrohttpd-dev \
    v4l-utils

RUN cd /var/tmp && \
    wget https://github.com/Motion-Project/motion/archive/release-$MOTION_VERSION.tar.gz && \
    tar xzf release-$MOTION_VERSION.tar.gz && \
    rm -f release-$MOTION_VERSION.tar.gz && \
    cd motion-release-$MOTION_VERSION && \
    autoreconf -fiv && \
    ./configure && \
    make && \
    make install && \
    cd /var/tmp && \
    rm -rf motion-release-$MOTION_VERSION

RUN pip install --no-cache \
    tornado==4.5.3 \
    six \
    motioneye==$MOTIONEYE_VERSION && \
    mkdir /etc/motioneye && \
    mkdir /var/lib/motioneye

COPY ./app/run.sh /run.sh
RUN chmod u+x /run.sh

EXPOSE 8765

VOLUME /etc/motioneye
VOLUME /var/lib/motioneye

CMD ["/run.sh"]

**Comment by kleini** [comment]
Compiling motion inside the container is not an option. That bloats the resulting image with build tools and motion sources. But this is a good starting point.

**Comment by ccrisan** [comment]
> @ccrisan I can make a PR with Python3 only support, it is straight forward - except for the tornado compatibility. That one takes a bit more testing to get it working with 5+.
> Just let me know if you are interested in such PR, and on which version (e.g. when 0.40 is released?).

@ualex73 versions 0.40 and probably another couple of subsequent versions will be reserved for bug fixes and minor features coming from adding Motion 4.2 support and dropping Motion 3.x support.

You can branch from current `dev` and prepare a Python3-only branch that we could keep testing and improving. I can't tell for now what motionEye version will drop Python 2 support. Maybe we'll need to rename the package or bump the version to 1.x or something. I'm open to suggestions.

**Comment by ualex73** [comment]
Ok, I created a new branch called 'python3', this works reasonable fine with Python 3.5+:
https://github.com/ualex73/motioneye/tree/python3

Only I still got some issues during configuration, because the Tornado 5.x+ uses asyncio now. When it goes all well it works, but when an error is detected it get a Tornado error that 'finish()' is called twice. I need to investigate further, because I am not a asyncio/tornado expert.

Anyway, if somebody wants to test it ... Please do :-)

**Comment by ualex73** [comment]
The python3 branch seems to be working fine with tornado 5.x and up, the asyncio stuff is sorted out now ;-)

**Comment by ilovelinux** [comment]
Devs please switch to Python 3 and close this pull request. I'm not gonna contribute if you will not switch to Python 3. In the meanwhile I can help with this pull request, I just can't understand what is missing to merge.

**Comment by kleini** [comment]
That about the automatically built Docker images? Do they work with these changes? I did not have the time to test this.

**Comment by ilovelinux** [comment]
> Compiling motion inside the container is not an option. That bloats the resulting image with build tools and motion sources. But this is a good starting point.

Can't we use https://github.com/Motion-Project/motion-docker ?

**Comment by kleini** [comment]
For x86 we can use that. But we need a solution for Raspberry Pi, too.

**Comment by ccrisan** [comment]
Let's track this on https://github.com/ccrisan/motioneye/pull/1571. I've manually merged conflicts and made some small adjustments.

**Comment by ccrisan** [comment]
Let's in fact track all Python3 compatibility changes on https://github.com/ccrisan/motioneye/pull/1572.

**Pull request closed without merging**
