### PR TITLE
Upgrade Docker image to newly released motion 4.1

### PR DESCRIPTION
**Pull request by kleini**
Based armhf Docker image on Debian because we do not have motion for armhf for Ubuntu.

I will test amd64 and armhf image this evening. The amd64 image will be used for my home video observation. The armhf image will be tested with qemu on x86 hardware and reduced resolution of 4k 20fps cameras because of CPU emulation.

### CODE REVIEW

**Comment by ccrisan** [comment]
Ready to be merged or do you plan further work or testing on this one?

**Comment by kleini** [comment]
@ccrisan as already said: I would like to test at least once the armhf image for functionality. I never did this before. I only use the amd64 image in production.

**Comment by kleini** [comment]
The Raspberry Pi firmware was missing in the Docker armhf image. Added it. Furthermore Dockerfile.local is now superfluous because the image contains always latest motioneye from related branch.
armhf

**Comment by kleini** [comment]
Ready to be merged.

**Comment by ccrisan** [comment]
Merged. Thanks!

**Comment by ccrisan** [comment]
@kleini coulld you please take a look over the [Install In Docker](https://github.com/ccrisan/motioneye/wiki/Install-In-Docker) wiki page when you find some spare time and see if you can come up with something more up-to-date with what we have now?

**Comment by kleini** [comment]
That's already in my TODO list.

**Pull request merged**
