### PR TITLE
Added support for telegram motion notifications (UI & Backend).

### PR DESCRIPTION
**Pull request by HawtDogFlvrWtr**
Added support for telegram motion notifications. Added interface pieces for api, chat id, photo capture support, and testing. Instructions for setup are included as buttons and question mark info. Built on the current email implementation using all standard libraries or those already used within motionEye. Full UI integration.

### CODE REVIEW

**Comment by think-free** [comment]
Any hope to have it merged ?
I don't want to rebuild the docker image if it will be merged soon and I need this functionality :p

**Comment by DaniW42** [comment]
Didnt't reviewed the code but this feature would be awesome! +1

**Comment by DaniW42** [comment]
@HawtDogFlvrWtr How can I test this? I edited all the changed files inside my `/usr/local/lib/python2.7/dist-packages/motioneye/` directory and did a restart but I can't see anything inside the webinterface... Or am I doing it wrong?

Running motioneye on a debian vm, installed by the original [Install On Debian](https://github.com/ccrisan/motioneye/wiki/Install-On-Debian) Tutorial

**Comment by HawtDogFlvrWtr** [comment]
You likely need to delete all of the .pyc files in that folder and restart the services. It compiles itself on first run and uses the pyc files if they exist, instead of the standard source.

**Comment by wokawoka** [comment]
Any hope that this contribution is merged? That's a killer feature

**Comment by HawtDogFlvrWtr** [comment]
It is very nice. I've been running it since I created it, and it's been working flawlessly ever since. Hopefully they merge soon.

**Comment by think-free** [comment]
About 6 month, please merge it :/

**Comment by ccrisan** [comment]
Let's have it merged then :) Thanks!

**Comment by myInstagramAlternative** [comment]
May I know when this feature will be available inside image file?

I'm not good with building stuff myself, I tried sending snapshot URL via sendPhoto API but it gets cached and doesn't want to update the image after that... cuz image URL/name is same, IDK.....

**Pull request merged**
