### PR TITLE
Added support for nvenc hardware encoding

### PR DESCRIPTION
**Pull request by HawtDogFlvrWtr**
Added support for nvenc hardware encoding as well as qsv. Disabled qsv user selection for now, as driver install and ffmpeg functions are an issue to compile and test. nvenc works fine though and decreases CPU usage exponentially. Implementation follows previously derived codec checking and interface display.

### CODE REVIEW

**Comment by ccrisan** [comment]
Looks good. Thanks!

**Comment by KC-inDomus** [comment]
Hi, I didn't understood if, after updating motionEye to this new version supporting nvec, you must do something in your config to activate this very new feature or not.

**Comment by HawtDogFlvrWtr** [comment]
@KC-inDomus you need to ensure you have the version of ffmpeg installed that includes the driver. You can see if you do by finding an rpm/deb file or by compiling a version with support.

https://devblogs.nvidia.com/nvidia-ffmpeg-transcoding-guide/

**Comment by KC-inDomus** [comment]
roger that. thanks a lot!

**Pull request merged**
