### PR TITLE
Added basic RTMP support to UI

### PR DESCRIPTION
**Pull request by mcd1992**
This allows RTMP network cameras to be added through the webui. Motion added RTMP support in v4.1 not sure if there should be a warning or something if a out-of-date motion is detected.

This commit doesn't have a proper test_rtmp_url function though. Since RTMP is a binary TCP stream we'll have to rely on some extra libs to do a proper test (unless tornado can handle raw TCP streams, I'd need to look into it more).

Also it looks like vscode took the liberty of removing a bunch of leftover whitespace. I can re-commit tomorrow if the commit diff is too ugly :stuck_out_tongue:

This does finally fix the issues with reolink cameras at least!
screenshot 2

See issue #885

### CODE REVIEW

**Comment by mcd1992** [comment]
Diff without whitespace fixes: https://github.com/ccrisan/motioneye/pull/1508/files?w=1

**Comment by aav7fl** [comment]
@ccrisan Would it be possible for these proposed changes to be reviewed or merged in? I'd love to see `rtmp` support so I can reduce frame corruption.

**Comment by flaektrem** [comment]
+1 on that! It would be awesome to get `rtmp `support. 100% Reolink cameras at home. @ccrisan @aav7fl

**Comment by ccrisan** [comment]
Thanks!

**Comment by flaektrem** [comment]
@ccrisan is it safe to use "dev" branch in docker?

**Comment by aav7fl** [comment]
> @ccrisan is it safe to use "dev" branch in docker?
> 
> Edit: I use docker hub. I think I cannot use the dev you just updated 😕
> 
> From the wiki:
> 
> > The automatically built images are available on Docker Hub https://hub.docker.com/r/ccrisan/motioneye/. The actual usable tags are master-amd64 and master-armhf. All other tags are from temporary feature branches and should not be used.

I think we just needed to wait a few hours for it. I just checked and it's there for me. The `rtmp` stream is working great now. :)

**Comment by flaektrem** [comment]
@aav7fl Good to hear its working now. So you just used the "dev" tag instead of "master" in docker hub?

@ccrisan Thank you very much my friend!

**Comment by aav7fl** [comment]
> @aav7fl Good to hear its working now. So you just used the "dev" tag instead of "master" in docker hub?


I used `ccrisan/motioneye:dev-amd64`. You can find all of the tags listed here: https://hub.docker.com/r/ccrisan/motioneye/tags

**Comment by Imperial-Guard** [comment]
How to conenct the camera? 

Should the config be like this:

Url: rtmp://192.168.1.150:1935/
Username: xxxx
Password: xxxx
Camera: RTMP/TCP Camera

**Comment by flaektrem** [comment]
@Imperial-Guard 
For me (Reolink RLC-410) this works:

Main stream URL: 
`rtmp://192.168.1.xxx/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=password`

Leave user and pass blank.

**Comment by jayjayseal** [comment]
@flaektrem i can confirm this works better then the default link i got from reolink. thanks. 
to date this still works instead of the usual link rtsp://username:password@<IP>//h264Preview_01_sub (or _main for highres).

**Pull request merged**
