### PR TITLE
Upgrade Docker image to newest Ubuntu

### PR DESCRIPTION
**Pull request by kleini**
Thanks for the Docker image of motioneye! I am using it the observation system at home. motioneye makes the use of the motion daemon a pleasure.

I am always curious to try newest versions of software. This time I tried to upgrade the Docker image to the newest Ubuntu base image. Furthermore I was able to simplify the creation of the Docker image a lot because Ubuntu Zesty already packages a lot of needed software.

The simplified creation also results in a much smaller size of the image. The previous image is 674M and my upgraded one is just 422M.
The image is automatically build on Docker Hub: https://hub.docker.com/r/kleini/motioneye/

My host system is running an outdated Ubuntu Trusty. Therefore I would like to contribute an upstart script for the motioneye Docker container, too.

### CODE REVIEW

**Comment by ccrisan** [comment]
Just like with other Docker contributions, I trust you with this one as I have no experience here. Given the relatively large amount of changes and the size of the contributed code, would you be willing to offer support for any Docker-related issues that may arise with motionEye from other users?

**Comment by kleini** [comment]
I had a quick look over the issues list and I found only this one: https://github.com/ccrisan/motioneye/issues/304. I found your repository on Docker Hub, too. As already stated in my initial pull request, building the image on Docker Hub is no problem at all. I can have a look into the Docker image for ARM architectures. OpenHAB e.g. does have images for ARM architectures.

 I overlooked the Dockerfile.local. Let me have a look into that before you merge this pull request. There should be a reason for a different Dockerfile for local builds.

And yes, I can take over Docker related issues of other motioneye users. As already stated, I am using the Docker image 24/7 at home.

**Comment by ccrisan** [comment]
Sounds great. Thanks.

**Comment by kleini** [comment]
I was able to built now even an image for the ARM architecture:
https://hub.docker.com/r/kleini/motioneye/tags/

**Comment by kleini** [comment]
The image should use latest motion daemon from here:
https://github.com/Motion-Project/motion/releases/download/release-4.0.1/yakkety_motion_4.0.1-1_amd64.deb

**Comment by kleini** [comment]
Furthermore the part around

    pip install motioneye

should be done using a multistage build to reduce final image size:
https://docs.docker.com/engine/userguide/eng-image/multistage-build/

**Comment by kleini** [comment]
@ccrisan I will upgrade today the creation of the x86 and armhf Docker images to latest Ubuntu and latest Motioneye. Afterwards I would like to get this merged back.

We need then a short session, so I can help you to set up the automated build with Travis CI and the push of the images to the Docker Hub. When do you have time for that? I see you're using a gmail address, mine is kleini76@gmail.com. A short chat conversation should be sufficient to get the automated build running.

**Comment by kleini** [comment]
I am still struggling to get the Docker image for Raspberry PI aka armhf working but the x86 Docker image already works with motioneye 0.38, motion 4.0.1 on Ubuntu 17.10 in production in my home video observation system.

**Pull request merged**
